from typing import TypedDict, List, Dict, Optional, Annotated, Literal
from pydantic import BaseModel, Field, field_validator
from datetime import datetime
from langgraph.graph.message import add_messages

# DATA MODELS
# These are the typed objects that agents produce and consume
# Pydantic validates every field - if an agent returns wrong data
# it gets caught here before it can cause problems downstream


class ErrorCluster(BaseModel):
    """
    Represents group of similar JS errors clustered together.
    Instead of 847 individual error events, we store 1 cluster.
    Produced by: Error Detector Agent
    """
    cluster_id: str
    error_message: str
    count: int
    page: str
    severity: Literal["critical", "high", "medium", "low"]
    revenue_impact_inr :int
    confidence: Literal["high", "medium", "low"]
    first_seen: datetime
    browser_breakdown: Dict[str, int]  # e.g. {"Chrome": 500, "Firefox": 200}
    resolved: bool = False

    @field_validator("revenue_impact_inr")
    @classmethod
    def revenue_must_be_valid(cls, v):
        # -1 is the special value meaning we dont have enough data to estimate 
        if v < -1:
            raise ValueError("revenue_impact_inr must be -1 or greater")
        # 1 crore per hour sanity cap — if LLM says more, something is wrong
        if v > 10_000_000:
            raise ValueError("revenue_impact_inr suspiciously high — possible hallucination")
        return v
    
class UserSegment(BaseModel):
    """
    Anamed group os users who share a behavioral pattern. 
    eg: 'cart_abandoned_high_value' = users who added ₹3000+ to cart but didn't buy.
    Produced by: Segmentation Agent
    """
    name: str
    user_ids: List[str]
    avg_cart_value: float 
    size: int 
    created_at: datetime
    campaign_sent_at: Optional[datetime] = None

class Insight(BaseModel):
    """
    A pattern or abservation generated by the insight Generator Agent.
    Backed by real events stored in Chroma DB - not hallucinated.
    Produced by: Insight Generator Agent
    """
    insight_id: str
    summary: str
    pattern_type: Literal["recurring", "new", "resolved", "anomaly"]
    confidence: Literal["high", "medium", "low"]
    # ID's of chromaDB documents that support this insight 
    # this makes every insight traceble- we can prove it with real data
    supporting_event_ids: List[str]
    created_at: datetime

class Campaign(BaseModel):
    """
    A multi-channel marketing message ready to send to a segment.
    Goes through human approval (HITL) before dispatch.
    Produced by: Campaign Writer Agent
    """
    campaign_id: str
    segment_name: str
    push_copy: str          # max 80 chars — for mobile push notification
    email_subject: str      # max 50 chars
    email_body: str
    sms_copy: str           # max 160 chars
    # pending_review → approved → sent (or rejected → re-draft)
    status: Literal["pending_review", "approved", "rejected", "sent"] = "pending_review"
    rejection_reason: Optional[str] = None  # if human rejects, reason goes here
    created_at: datetime = Field(default_factory=datetime.now)

    @field_validator("push_copy")
    @classmethod
    def push_must_be_short(cls, v):
        # push notifications over 80 chars get truncated on most devices
        if len(v) > 80:
            raise ValueError(f"push_copy too long ({len(v)} chars). Max 80.")
        return v

    @field_validator("email_subject")
    @classmethod
    def subject_must_be_short(cls, v):
        if len(v) > 50:
            raise ValueError(f"email_subject too long ({len(v)} chars). Max 50.")
        return v

    @field_validator("sms_copy")
    @classmethod
    def sms_must_be_short(cls, v):
        if len(v) > 160:
            raise ValueError(f"sms_copy too long ({len(v)} chars). Max 160.")
        return v


class AlertRecord(BaseModel):
    """
    A log of every alert that was sent.
    Used by Alert Dispatcher to enforce the 15-minute cooldown
    so we don't spam Slack with the same error repeatedly.
    Produced by: Alert Dispatcher Agent
    """
    cluster_id: str
    sent_at: datetime
    channel: Literal["slack", "email"]
    severity: str
    message_preview: str                # first 100 chars of what was sent

# SECTION 2 — THE MASTER STATE
# This is the single object that LangGraph manages.
# Think of it as the shared whiteboard all agents read and write.

class EcomSenseState(TypedDict):

    # Latest batch of events pulled from redis stream
    # Ingest node fills this. Agents can read but not modify.
    raw_events: List[Dict]

    # Agent outputs
    # Each agent ONLY writes to its own key - never touches other agents keys
    error_clusters: List[ErrorCluster]
    segments: Dict[str, UserSegment]
    insights: List[Insight]
    pending_campaigns: List[Campaign]
    alerts_sent: List[AlertRecord]

    # Orchestrator metadata 
    # the orchestrator reads these to decide which agent to run next, but agents don't touch these
    last_insight_run: Optional[datetime]
    last_segment_run: Optional[datetime]
    current_task: str
    iteration_count: int 

    thread_id: str 

    messages: Annotated[List, add_messages]


def get_initial_state(thread_id: str) -> EcomSenseState:
    """
    Creates a fresh empty state for a new conversation thread.
    Called when a user opens the dashboard for the first time.
    """
    return EcomSenseState(
        raw_events=[],
        error_clusters=[],
        segments={},
        insights=[],
        pending_campaigns=[],
        alerts_sent=[],
        last_insight_run=None,
        last_segment_run=None,
        current_task="idle",
        iteration_count=0,
        thread_id=thread_id,
        messages=[],
    )
